// Generated by CoffeeScript 1.3.3
(function() {
  var Blog, Post;

  $(function() {
    var blog_urls, url, _i, _len;
    blog_urls = ["http://joshmcarthur.com/feed/index.xml"];
    this.blogs || (this.blogs = []);
    for (_i = 0, _len = blog_urls.length; _i < _len; _i++) {
      url = blog_urls[_i];
      this.blogs.push(new Blog(url));
    }
    return console.log(this.blogs);
  });

  Blog = (function() {

    function Blog(url) {
      var _this = this;
      this.url = url;
      this.items = [];
      $.getJSON(this.yql_url(), function(yql_json) {
        var post_data, _i, _len, _ref, _results;
        _ref = $(yql_json.results[0]).find('entry');
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          post_data = _ref[_i];
          _results.push(_this.items.push(new Post(post_data)));
        }
        return _results;
      });
    }

    Blog.prototype.yql_url = function() {
      return 'http://query.yahooapis.com/v1/public/yql?q=' + encodeURIComponent('select * from xml where url="' + this.url + '"') + '&format=xml&callback=?';
    };

    return Blog;

  })();

  Post = (function() {

    function Post(data) {
      data = $(data);
      this.title = data.find('title').text();
      this.link = data.find('link').attr('href');
      this.date = data.find('updated').text();
    }

    return Post;

  })();

}).call(this);
